services:
  - type: web
    name: crop-yield-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn prediction:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16